---
detectors:
  IrresponsibleModule:
    enabled: false  # We use YARD for documentation, not inline comments

  TooManyStatements:
    max_statements: 18  # Render methods building UI are inherently sequential

  ManualDispatch:
    enabled: false  # respond_to? checks on IO objects are defensive Ruby practice

  Attribute:
    enabled: false  # Writable attributes for config are intentional

  TooManyInstanceVariables:
    max_instance_variables: 14  # Complex prompt classes need state for cursor, scroll, selection, etc.

  FeatureEnvy:
    enabled: false  # Transformation/formatting methods naturally reference their input more than self

  TooManyConstants:
    enabled: false  # Symbols module is intentionally constant-heavy

  UncommunicativeParameterName:
    accept:
      - n  # Standard for counts
      - x  # Standard for coordinates
      - y  # Standard for coordinates

  UncommunicativeVariableName:
    accept:
      - _  # Ruby convention for ignored values
      - o  # Used in lambda definitions
      - s  # Spinner variable
      - v  # Value in lambda

  DataClump:
    enabled: false  # Common parameters like message/output are intentional

  ControlParameter:
    enabled: false  # Control flow based on params is normal for prompts

  DuplicateMethodCall:
    max_calls: 5  # Allow duplication for clarity in pattern-matching scenarios

  UtilityFunction:
    enabled: false  # Helper methods in classes are fine

  InstanceVariableAssumption:
    enabled: false  # Subclass patterns are acceptable

  NilCheck:
    enabled: false  # Nil checks are sometimes clearer than safe navigation

  UnusedParameters:
    enabled: false  # Base class defines interface for subclasses

  BooleanParameter:
    enabled: false  # Boolean params are idiomatic for options

  LongParameterList:
    enabled: false  # CLI prompt initializers legitimately need many parameters

  RepeatedConditional:
    max_ifs: 4

  TooManyMethods:
    max_methods: 26

exclude_paths:
  - spec
